# 运行模式(debug:调试,test:测试,release:正式)
runmode = "debug"

# 启动时是否打印配置参数
print = true

[s.a.b.c]
a = "1"

[[s.a.b.d]]
a = "1"

[[s.a.b.d]]
a = "2"

[[s.a.b.e]]
c = "1"

[[s.a.b.e]]
c = "2"

[[s.b.b.e]]
n = "3"

[[s.b.b.e]]
n = "4"

[[s.b.a.e]]
n = "5"

[[s.c.a.e]]
n = "5"

[[s.c.a.e]]
n = "6"

[[s.c.a.e]]
n = "7"

