name: build-tag

on:
  push:
    # branches: [ main ]
    tags: [ "*-*" ]

#  https://github.com/suisrc/zgg/

env:
  IMAGE_NAME: suisrc/k8skit
  GITHUB_REGISTRY: ghcr.io
  DOCKER_REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo ${TAG_NAME##*-} > app/vname
          echo ${TAG_NAME%%-*} > app/version
          echo "IMAGE_VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "appname: `cat app/vname`, version: `cat app/version`"
          sed -i "s|zgg|`cat app/vname`|g" Dockerfile
          docker build -t image --no-cache .

      #-${{ github.job }}
      - name: Push github image
        run: |
          REGISTRY_URL=$GITHUB_REGISTRY
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$GITHUB_REPOSITORY
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push docker image
        run: |
          REGISTRY_URL=$DOCKER_REGISTRY
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      # zgg 的 tag 是 会同步到其引用的项目中，所以这里个 tag 只是标注激活构建，因此构建成功后，应该删除掉 tag
      - name: Delete tag reference via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs/tags/$TAG_NAME"
