name: build

on:
  push:
    # branches: [ main ]
    tags: [ "*-*" ]

#  https://github.com/suisrc/zgg/
#  https://github.com/suisrc/zgg/pkgs/container/k8s

env:
  IMAGE_NAME: suisrc/k8skit
  GITHUB_REGISTRY: ghcr.io
  DOCKER_REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo ${TAG_NAME##*-} > vname
          echo ${TAG_NAME%%-*} > version
          echo "k8skit, appname: `cat vname`, version: `cat version`"
          sed -i "s|k8skit|`cat vname`|g" Dockerfile
          docker build -t image --no-cache .

      #-${{ github.job }}
      - name: Push github image
        run: |
          REGISTRY_URL=$GITHUB_REGISTRY
          IMAGE_VERSION=$TAG_NAME
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_URL -u ${{ github.actor }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push docker image
        run: |
          REGISTRY_URL=$DOCKER_REGISTRY
          IMAGE_VERSION=$TAG_NAME
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login $REGISTRY_URL -u ${{ secrets.DOCKER_USER }} --password-stdin

          IMAGE_ID=$REGISTRY_URL/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          VERSION=$IMAGE_VERSION
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
