name: build-all

on:
  push:
    # branches: [ main ]
    tags: [ "v*" ]

#  https://github.com/suisrc/zgg/

env:
  IMAGE_NAME: suisrc/k8skit
  GITHUB_REGISTRY: ghcr.io
  DOCKER_REGISTRY: docker.io

jobs:
  front2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use build-auto
        uses: ./.github/actions/build-auto
        with:
          docker_user: ${{ secrets.DOCKER_USER }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
  kwdog2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use build-auto
        uses: ./.github/actions/build-auto
        with:
          docker_user: ${{ secrets.DOCKER_USER }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
  kwlog2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use build-auto
        uses: ./.github/actions/build-auto
        with:
          docker_user: ${{ secrets.DOCKER_USER }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
